### ISSUE TITLE
Multiple threads with `--test-threads`

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/libtest-mimic#2]
Currently, the argument `--test-threads` is ignored. This shouldn't be the case.

**Comment by Nadrieril** [comment]
@LukasKalbertodt Thanks for this library, this is exactly what I needed!

I'm trying to implement multithreading because that would make a huge difference for my use-case. However that would entail a breaking change in the signature of `run_tests` because we would need `D` and the closure to be `'static + Send + Sync`. Is that ok or would you prefer I write `run_tests_threaded` with the new signature and keep both functions ?

**Comment by LukasKalbertodt** [comment]
@Nadrieril Awesome! 

No, go ahead and change the signature. The signature without those bounds was a mistake (a lack of foresight) on my side. I can simply release as a new major version.
