### ISSUE TITLE
Run target function with no test harness

### ISSUE THREAD

**Issue by jedbrown** [LukasKalbertodt/libtest-mimic#31]
I'd like to use libtest-mimic to support MPI, which will involve running a function in the current executable with no test harness semantics. If I were to add such a thing to `simple.rs`, the new `check_mpi()` would involve running a `Command` that amounts to
```
mpiexec -n 2 target/debug/examples/simple-60c49fe0be82d931 --just-run-function-with-no-harness main_for_check_mpi
```
This creates multiple processes that communicate between themselves. The `check_mpi()` would check that they complete successfully and produce desired output. I want `main_for_check_mpi()` to be able to live in the same source file and executable as `check_mpi()`, but haven't found a way to do this with libtest-mimic.

Is this a use case that might be in scope for libtest-mimic? Either way, do you have implementation suggestions?

**Comment by jedbrown** [comment]
To be more specific, here are two possible designs. Both would add a new struct `EntryPoint` constructed something like `EntryPoint::new("this_function", this_function_main)`.
1. `Trial::test_with_entry_points("check_thing", check_thing, &[entry])` and use normal `libtest_mimic::run`.
2. `libtest_mimic::run_with_entry_points(&args, tests, entry_points)`

The former is more localized, but several tests might use the same entry point, so we'd either be creating redundant `EntryPoint`s or the caller needs to manage them to avoid duplicates. Any preference between these two or a different design (or if this is out of scope for libtest_mimic)?

**Comment by LukasKalbertodt** [comment]
I'm afraid that I'm still not sure I understand what exactly you are describing. My understanding is:

- You want the test executable, when no CLI arguments are given, or when only the currently supported CLI arguments are given, to just behave like it does now.
- However, if a special CLI argument is given (you called it `--just-run-function-with-no-harness`), then the whole test running logic is skipped and `main` will just call a specific function and that's it.

In that case, this would be out of scope for this library IMO, but in particular because it is really easy to add that on top. You can just check `std::env::args()` yourself to see if this special CLI argument is given. And if it is, call the function yourself. If not, then just do the other stuff, i.e. call `libtest_mimic::Arguments::from_args()` and later `libtest_mimic::run()`. If you want to be a little more fancy about it, I guess you can also use `clap` with some special attributes to inline `libtests_mimic::Arguments` into your struct or something like that.

Is my understanding correct?

**Comment by jedbrown** [comment]
Yeah, that's right. I wanted to be able to define the entry point where I register `Trial::test` and it felt too clumsy to do outside. I've been caught on other things this past month, but will try using this construction and I think it'll be able to meet my needs.
